/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.9.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QGraphicsView *gvMain;
    QFrame *res_frame;
    QGroupBox *groupBox_6;
    QComboBox *res_combobox;
    QFrame *frame_2;
    QGroupBox *groupBox_4;
    QFrame *frame_3;
    QGroupBox *groupBox_5;
    QLabel *label;
    QSlider *gamma_horizontalSlider;
    QSpinBox *spinBox_gamma;
    QSlider *contrast_horizontalSlider;
    QLabel *label_2;
    QSpinBox *spinBox_contrast;
    QFrame *frame_trigger;
    QGroupBox *groupBox_9;
    QRadioButton *radioButton_collect;
    QRadioButton *radioButton_software_trigger;
    QRadioButton *radioButton_trigger_hardware;
    QPushButton *software_trigger_once_button;
    QLabel *label_27;
    QFrame *flashlight;
    QGroupBox *groupBox_7;
    QFrame *flashlight_polarity;
    QGroupBox *groupBox_8;
    QRadioButton *flashlight_h;
    QRadioButton *flashlight_l;
    QLabel *label_26;
    QRadioButton *flashlight_auto;
    QRadioButton *flashlight_manual;
    QFrame *frame_5;
    QGroupBox *groupBox_11;
    QFrame *frame_exposure_mode;
    QGroupBox *groupBox_10;
    QRadioButton *exposure_mode_auto;
    QRadioButton *exposure_mode_manual;
    QFrame *exposure_auto;
    QGroupBox *groupBox_12;
    QLabel *label_3;
    QSlider *AE_horizontalSlider;
    QSpinBox *AE_spinBox;
    QCheckBox *flicker_checkBox;
    QRadioButton *radioButton_50HZ;
    QRadioButton *radioButton_60HZ;
    QFrame *exposure_manual;
    QGroupBox *groupBox_13;
    QLabel *label_4;
    QLabel *label_5;
    QSlider *horizontalSlider_gain;
    QSlider *horizontalSlider_exposure_time;
    QSpinBox *spinBox_gain;
    QLineEdit *lineEdit_exposure_time;
    QFrame *frame_9;
    QGroupBox *groupBox_2;
    QCheckBox *checkBox_isp_h;
    QCheckBox *checkBox_isp_v;
    QLabel *label_6;
    QSlider *horizontalSlider_isp_acutance;
    QSpinBox *spinBox_isp_acutance;
    QFrame *frame_10;
    QGroupBox *groupBox;
    QRadioButton *radioButton_B;
    QRadioButton *radioButton_A;
    QRadioButton *radioButton_C;
    QPushButton *pushButton_para_save;
    QPushButton *pushButton_para_acquiesce;
    QPushButton *pushButton_para_load;
    QRadioButton *radioButton_D;
    QFrame *frame_wb;
    QGroupBox *groupBox_3;
    QLabel *label_7;
    QLabel *label_8;
    QRadioButton *radioButton_AWB_auto;
    QRadioButton *radioButton_13;
    QPushButton *AWB_once_button;
    QLabel *label_9;
    QLabel *label_10;
    QSlider *horizontalSlider_gain_r;
    QSpinBox *spinBox_gain_r;
    QSlider *horizontalSlider_gain_g;
    QSpinBox *spinBox_gain_g;
    QLabel *label_11;
    QSlider *horizontalSlider_gain_b;
    QSpinBox *spinBox_gain_b;
    QLabel *label_12;
    QSlider *horizontalSlider_saturation;
    QSpinBox *spinBox_saturation;
    QFrame *frame_12;
    QGroupBox *groupBox_14;
    QPushButton *pushButton_snap_catch;
    QRadioButton *radioButton_16;
    QRadioButton *radioButton_17;
    QPushButton *pushButton_8;
    QCheckBox *checkBox_4;
    QLabel *label_19;
    QLabel *label_20;
    QCheckBox *checkBox_5;
    QLineEdit *snap_path_lineEdit;
    QPushButton *pushButton_snap_path;
    QLabel *label_21;
    QLineEdit *lineEdit_2;
    QLabel *label_22;
    QRadioButton *radioButton_jpg;
    QRadioButton *radioButton_png;
    QRadioButton *radioButton_bmp;
    QRadioButton *radioButton_raw;
    QFrame *frame_speed;
    QGroupBox *groupBox_speed;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->setEnabled(true);
        MainWindow->resize(1440, 630);
        QSizePolicy sizePolicy(QSizePolicy::Policy::Preferred, QSizePolicy::Policy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(1440, 630));
        MainWindow->setMaximumSize(QSize(1440, 630));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName("centralWidget");
        gvMain = new QGraphicsView(centralWidget);
        gvMain->setObjectName("gvMain");
        gvMain->setGeometry(QRect(10, 0, 800, 600));
        QBrush brush(QColor(127, 127, 127, 255));
        brush.setStyle(Qt::BrushStyle::SolidPattern);
        gvMain->setBackgroundBrush(brush);
        res_frame = new QFrame(centralWidget);
        res_frame->setObjectName("res_frame");
        res_frame->setGeometry(QRect(830, 20, 250, 45));
        res_frame->setFrameShape(QFrame::Shape::StyledPanel);
        res_frame->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_6 = new QGroupBox(res_frame);
        groupBox_6->setObjectName("groupBox_6");
        groupBox_6->setGeometry(QRect(0, 0, 250, 45));
        res_combobox = new QComboBox(groupBox_6);
        res_combobox->setObjectName("res_combobox");
        res_combobox->setGeometry(QRect(5, 7, 240, 30));
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName("frame_2");
        frame_2->setGeometry(QRect(1090, 20, 330, 80));
        frame_2->setFrameShape(QFrame::Shape::StyledPanel);
        frame_2->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_4 = new QGroupBox(frame_2);
        groupBox_4->setObjectName("groupBox_4");
        groupBox_4->setGeometry(QRect(0, 0, 330, 80));
        frame_3 = new QFrame(groupBox_4);
        frame_3->setObjectName("frame_3");
        frame_3->setGeometry(QRect(5, 5, 320, 70));
        frame_3->setFrameShape(QFrame::Shape::StyledPanel);
        frame_3->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_5 = new QGroupBox(frame_3);
        groupBox_5->setObjectName("groupBox_5");
        groupBox_5->setGeometry(QRect(0, 0, 320, 70));
        label = new QLabel(groupBox_5);
        label->setObjectName("label");
        label->setGeometry(QRect(20, 10, 40, 20));
        gamma_horizontalSlider = new QSlider(groupBox_5);
        gamma_horizontalSlider->setObjectName("gamma_horizontalSlider");
        gamma_horizontalSlider->setGeometry(QRect(70, 10, 180, 20));
        gamma_horizontalSlider->setOrientation(Qt::Orientation::Horizontal);
        spinBox_gamma = new QSpinBox(groupBox_5);
        spinBox_gamma->setObjectName("spinBox_gamma");
        spinBox_gamma->setGeometry(QRect(260, 10, 50, 20));
        contrast_horizontalSlider = new QSlider(groupBox_5);
        contrast_horizontalSlider->setObjectName("contrast_horizontalSlider");
        contrast_horizontalSlider->setGeometry(QRect(70, 40, 180, 20));
        contrast_horizontalSlider->setOrientation(Qt::Orientation::Horizontal);
        label_2 = new QLabel(groupBox_5);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(20, 40, 50, 20));
        spinBox_contrast = new QSpinBox(groupBox_5);
        spinBox_contrast->setObjectName("spinBox_contrast");
        spinBox_contrast->setGeometry(QRect(260, 40, 50, 20));
        frame_trigger = new QFrame(centralWidget);
        frame_trigger->setObjectName("frame_trigger");
        frame_trigger->setGeometry(QRect(830, 90, 250, 100));
        frame_trigger->setFrameShape(QFrame::Shape::StyledPanel);
        frame_trigger->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_9 = new QGroupBox(frame_trigger);
        groupBox_9->setObjectName("groupBox_9");
        groupBox_9->setGeometry(QRect(0, 0, 250, 100));
        radioButton_collect = new QRadioButton(groupBox_9);
        radioButton_collect->setObjectName("radioButton_collect");
        radioButton_collect->setGeometry(QRect(10, 5, 100, 20));
        radioButton_software_trigger = new QRadioButton(groupBox_9);
        radioButton_software_trigger->setObjectName("radioButton_software_trigger");
        radioButton_software_trigger->setGeometry(QRect(10, 25, 100, 20));
        radioButton_trigger_hardware = new QRadioButton(groupBox_9);
        radioButton_trigger_hardware->setObjectName("radioButton_trigger_hardware");
        radioButton_trigger_hardware->setEnabled(true);
        radioButton_trigger_hardware->setGeometry(QRect(10, 45, 80, 20));
        software_trigger_once_button = new QPushButton(groupBox_9);
        software_trigger_once_button->setObjectName("software_trigger_once_button");
        software_trigger_once_button->setGeometry(QRect(10, 65, 100, 27));
        label_27 = new QLabel(groupBox_9);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(120, 5, 90, 17));
        flashlight = new QFrame(groupBox_9);
        flashlight->setObjectName("flashlight");
        flashlight->setGeometry(QRect(110, 20, 130, 75));
        flashlight->setFrameShape(QFrame::Shape::StyledPanel);
        flashlight->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_7 = new QGroupBox(flashlight);
        groupBox_7->setObjectName("groupBox_7");
        groupBox_7->setGeometry(QRect(0, 0, 130, 75));
        flashlight_polarity = new QFrame(groupBox_7);
        flashlight_polarity->setObjectName("flashlight_polarity");
        flashlight_polarity->setGeometry(QRect(10, 40, 110, 30));
        flashlight_polarity->setFrameShape(QFrame::Shape::StyledPanel);
        flashlight_polarity->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_8 = new QGroupBox(groupBox_7);
        groupBox_8->setObjectName("groupBox_8");
        groupBox_8->setGeometry(QRect(10, 40, 110, 30));
        flashlight_h = new QRadioButton(groupBox_8);
        flashlight_h->setObjectName("flashlight_h");
        flashlight_h->setGeometry(QRect(10, 5, 40, 22));
        flashlight_l = new QRadioButton(groupBox_8);
        flashlight_l->setObjectName("flashlight_l");
        flashlight_l->setGeometry(QRect(60, 5, 50, 22));
        label_26 = new QLabel(groupBox_7);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(10, 25, 62, 17));
        flashlight_auto = new QRadioButton(groupBox_7);
        flashlight_auto->setObjectName("flashlight_auto");
        flashlight_auto->setGeometry(QRect(5, 5, 55, 22));
        flashlight_manual = new QRadioButton(groupBox_7);
        flashlight_manual->setObjectName("flashlight_manual");
        flashlight_manual->setGeometry(QRect(70, 5, 55, 22));
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName("frame_5");
        frame_5->setGeometry(QRect(830, 215, 270, 205));
        frame_5->setFrameShape(QFrame::Shape::StyledPanel);
        frame_5->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_11 = new QGroupBox(frame_5);
        groupBox_11->setObjectName("groupBox_11");
        groupBox_11->setGeometry(QRect(0, 0, 270, 205));
        frame_exposure_mode = new QFrame(groupBox_11);
        frame_exposure_mode->setObjectName("frame_exposure_mode");
        frame_exposure_mode->setGeometry(QRect(10, 10, 250, 35));
        frame_exposure_mode->setFrameShape(QFrame::Shape::StyledPanel);
        frame_exposure_mode->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_10 = new QGroupBox(frame_exposure_mode);
        groupBox_10->setObjectName("groupBox_10");
        groupBox_10->setGeometry(QRect(0, 0, 250, 35));
        exposure_mode_auto = new QRadioButton(groupBox_10);
        exposure_mode_auto->setObjectName("exposure_mode_auto");
        exposure_mode_auto->setGeometry(QRect(10, 7, 109, 22));
        exposure_mode_manual = new QRadioButton(groupBox_10);
        exposure_mode_manual->setObjectName("exposure_mode_manual");
        exposure_mode_manual->setGeometry(QRect(140, 7, 109, 22));
        exposure_auto = new QFrame(groupBox_11);
        exposure_auto->setObjectName("exposure_auto");
        exposure_auto->setGeometry(QRect(10, 55, 250, 70));
        exposure_auto->setFrameShape(QFrame::Shape::StyledPanel);
        exposure_auto->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_12 = new QGroupBox(exposure_auto);
        groupBox_12->setObjectName("groupBox_12");
        groupBox_12->setGeometry(QRect(0, 0, 250, 70));
        label_3 = new QLabel(groupBox_12);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 10, 60, 20));
        AE_horizontalSlider = new QSlider(groupBox_12);
        AE_horizontalSlider->setObjectName("AE_horizontalSlider");
        AE_horizontalSlider->setGeometry(QRect(70, 10, 120, 20));
        AE_horizontalSlider->setMaximum(300);
        AE_horizontalSlider->setValue(99);
        AE_horizontalSlider->setOrientation(Qt::Orientation::Horizontal);
        AE_spinBox = new QSpinBox(groupBox_12);
        AE_spinBox->setObjectName("AE_spinBox");
        AE_spinBox->setGeometry(QRect(190, 10, 50, 20));
        AE_spinBox->setMaximum(300);
        flicker_checkBox = new QCheckBox(groupBox_12);
        flicker_checkBox->setObjectName("flicker_checkBox");
        flicker_checkBox->setGeometry(QRect(10, 40, 70, 20));
        radioButton_50HZ = new QRadioButton(groupBox_12);
        radioButton_50HZ->setObjectName("radioButton_50HZ");
        radioButton_50HZ->setGeometry(QRect(80, 40, 60, 20));
        radioButton_60HZ = new QRadioButton(groupBox_12);
        radioButton_60HZ->setObjectName("radioButton_60HZ");
        radioButton_60HZ->setGeometry(QRect(140, 40, 70, 20));
        exposure_manual = new QFrame(groupBox_11);
        exposure_manual->setObjectName("exposure_manual");
        exposure_manual->setEnabled(true);
        exposure_manual->setGeometry(QRect(10, 135, 250, 60));
        exposure_manual->setFrameShape(QFrame::Shape::StyledPanel);
        exposure_manual->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_13 = new QGroupBox(exposure_manual);
        groupBox_13->setObjectName("groupBox_13");
        groupBox_13->setGeometry(QRect(0, 0, 250, 60));
        label_4 = new QLabel(groupBox_13);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(10, 10, 60, 20));
        label_5 = new QLabel(groupBox_13);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(10, 35, 60, 20));
        horizontalSlider_gain = new QSlider(groupBox_13);
        horizontalSlider_gain->setObjectName("horizontalSlider_gain");
        horizontalSlider_gain->setGeometry(QRect(70, 10, 110, 20));
        horizontalSlider_gain->setOrientation(Qt::Orientation::Horizontal);
        horizontalSlider_exposure_time = new QSlider(groupBox_13);
        horizontalSlider_exposure_time->setObjectName("horizontalSlider_exposure_time");
        horizontalSlider_exposure_time->setGeometry(QRect(70, 35, 110, 20));
        horizontalSlider_exposure_time->setOrientation(Qt::Orientation::Horizontal);
        spinBox_gain = new QSpinBox(groupBox_13);
        spinBox_gain->setObjectName("spinBox_gain");
        spinBox_gain->setGeometry(QRect(180, 10, 65, 20));
        lineEdit_exposure_time = new QLineEdit(groupBox_13);
        lineEdit_exposure_time->setObjectName("lineEdit_exposure_time");
        lineEdit_exposure_time->setGeometry(QRect(180, 30, 65, 25));
        frame_9 = new QFrame(centralWidget);
        frame_9->setObjectName("frame_9");
        frame_9->setEnabled(true);
        frame_9->setGeometry(QRect(830, 445, 270, 60));
        frame_9->setFrameShape(QFrame::Shape::StyledPanel);
        frame_9->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_2 = new QGroupBox(frame_9);
        groupBox_2->setObjectName("groupBox_2");
        groupBox_2->setGeometry(QRect(0, 0, 270, 60));
        checkBox_isp_h = new QCheckBox(groupBox_2);
        checkBox_isp_h->setObjectName("checkBox_isp_h");
        checkBox_isp_h->setGeometry(QRect(20, 10, 90, 20));
        checkBox_isp_v = new QCheckBox(groupBox_2);
        checkBox_isp_v->setObjectName("checkBox_isp_v");
        checkBox_isp_v->setGeometry(QRect(160, 10, 90, 20));
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(20, 35, 60, 20));
        horizontalSlider_isp_acutance = new QSlider(groupBox_2);
        horizontalSlider_isp_acutance->setObjectName("horizontalSlider_isp_acutance");
        horizontalSlider_isp_acutance->setGeometry(QRect(60, 35, 141, 20));
        horizontalSlider_isp_acutance->setOrientation(Qt::Orientation::Horizontal);
        spinBox_isp_acutance = new QSpinBox(groupBox_2);
        spinBox_isp_acutance->setObjectName("spinBox_isp_acutance");
        spinBox_isp_acutance->setGeometry(QRect(210, 35, 50, 20));
        frame_10 = new QFrame(centralWidget);
        frame_10->setObjectName("frame_10");
        frame_10->setGeometry(QRect(830, 525, 270, 70));
        frame_10->setFrameShape(QFrame::Shape::StyledPanel);
        frame_10->setFrameShadow(QFrame::Shadow::Raised);
        groupBox = new QGroupBox(frame_10);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(0, 0, 270, 70));
        radioButton_B = new QRadioButton(groupBox);
        radioButton_B->setObjectName("radioButton_B");
        radioButton_B->setGeometry(QRect(70, 12, 40, 20));
        radioButton_A = new QRadioButton(groupBox);
        radioButton_A->setObjectName("radioButton_A");
        radioButton_A->setGeometry(QRect(20, 12, 40, 20));
        radioButton_C = new QRadioButton(groupBox);
        radioButton_C->setObjectName("radioButton_C");
        radioButton_C->setGeometry(QRect(20, 40, 40, 20));
        pushButton_para_save = new QPushButton(groupBox);
        pushButton_para_save->setObjectName("pushButton_para_save");
        pushButton_para_save->setGeometry(QRect(120, 10, 70, 25));
        pushButton_para_acquiesce = new QPushButton(groupBox);
        pushButton_para_acquiesce->setObjectName("pushButton_para_acquiesce");
        pushButton_para_acquiesce->setGeometry(QRect(190, 10, 70, 25));
        pushButton_para_load = new QPushButton(groupBox);
        pushButton_para_load->setObjectName("pushButton_para_load");
        pushButton_para_load->setGeometry(QRect(120, 40, 140, 25));
        radioButton_D = new QRadioButton(groupBox);
        radioButton_D->setObjectName("radioButton_D");
        radioButton_D->setGeometry(QRect(70, 42, 40, 20));
        frame_wb = new QFrame(centralWidget);
        frame_wb->setObjectName("frame_wb");
        frame_wb->setGeometry(QRect(1110, 120, 310, 235));
        frame_wb->setFrameShape(QFrame::Shape::StyledPanel);
        frame_wb->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_3 = new QGroupBox(frame_wb);
        groupBox_3->setObjectName("groupBox_3");
        groupBox_3->setGeometry(QRect(0, 0, 310, 235));
        label_7 = new QLabel(groupBox_3);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(15, 15, 290, 20));
        label_8 = new QLabel(groupBox_3);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(20, 40, 60, 20));
        radioButton_AWB_auto = new QRadioButton(groupBox_3);
        radioButton_AWB_auto->setObjectName("radioButton_AWB_auto");
        radioButton_AWB_auto->setGeometry(QRect(80, 40, 60, 20));
        radioButton_13 = new QRadioButton(groupBox_3);
        radioButton_13->setObjectName("radioButton_13");
        radioButton_13->setEnabled(false);
        radioButton_13->setGeometry(QRect(170, 40, 60, 20));
        AWB_once_button = new QPushButton(groupBox_3);
        AWB_once_button->setObjectName("AWB_once_button");
        AWB_once_button->setGeometry(QRect(15, 65, 281, 25));
        label_9 = new QLabel(groupBox_3);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(20, 100, 60, 20));
        label_10 = new QLabel(groupBox_3);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(20, 130, 60, 20));
        horizontalSlider_gain_r = new QSlider(groupBox_3);
        horizontalSlider_gain_r->setObjectName("horizontalSlider_gain_r");
        horizontalSlider_gain_r->setGeometry(QRect(80, 100, 160, 20));
        horizontalSlider_gain_r->setMaximum(400);
        horizontalSlider_gain_r->setPageStep(10);
        horizontalSlider_gain_r->setOrientation(Qt::Orientation::Horizontal);
        spinBox_gain_r = new QSpinBox(groupBox_3);
        spinBox_gain_r->setObjectName("spinBox_gain_r");
        spinBox_gain_r->setGeometry(QRect(250, 100, 50, 20));
        spinBox_gain_r->setMaximum(400);
        horizontalSlider_gain_g = new QSlider(groupBox_3);
        horizontalSlider_gain_g->setObjectName("horizontalSlider_gain_g");
        horizontalSlider_gain_g->setGeometry(QRect(80, 130, 160, 20));
        horizontalSlider_gain_g->setMaximum(400);
        horizontalSlider_gain_g->setOrientation(Qt::Orientation::Horizontal);
        spinBox_gain_g = new QSpinBox(groupBox_3);
        spinBox_gain_g->setObjectName("spinBox_gain_g");
        spinBox_gain_g->setGeometry(QRect(250, 130, 50, 20));
        spinBox_gain_g->setMaximum(400);
        label_11 = new QLabel(groupBox_3);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(20, 160, 60, 20));
        horizontalSlider_gain_b = new QSlider(groupBox_3);
        horizontalSlider_gain_b->setObjectName("horizontalSlider_gain_b");
        horizontalSlider_gain_b->setGeometry(QRect(80, 160, 160, 20));
        horizontalSlider_gain_b->setMaximum(400);
        horizontalSlider_gain_b->setOrientation(Qt::Orientation::Horizontal);
        spinBox_gain_b = new QSpinBox(groupBox_3);
        spinBox_gain_b->setObjectName("spinBox_gain_b");
        spinBox_gain_b->setGeometry(QRect(250, 160, 50, 20));
        spinBox_gain_b->setMaximum(400);
        label_12 = new QLabel(groupBox_3);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(20, 200, 60, 20));
        horizontalSlider_saturation = new QSlider(groupBox_3);
        horizontalSlider_saturation->setObjectName("horizontalSlider_saturation");
        horizontalSlider_saturation->setGeometry(QRect(80, 200, 160, 20));
        horizontalSlider_saturation->setMaximum(200);
        horizontalSlider_saturation->setOrientation(Qt::Orientation::Horizontal);
        spinBox_saturation = new QSpinBox(groupBox_3);
        spinBox_saturation->setObjectName("spinBox_saturation");
        spinBox_saturation->setGeometry(QRect(250, 200, 50, 20));
        spinBox_saturation->setMaximum(200);
        frame_12 = new QFrame(centralWidget);
        frame_12->setObjectName("frame_12");
        frame_12->setGeometry(QRect(1110, 375, 310, 165));
        frame_12->setFrameShape(QFrame::Shape::StyledPanel);
        frame_12->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_14 = new QGroupBox(frame_12);
        groupBox_14->setObjectName("groupBox_14");
        groupBox_14->setGeometry(QRect(0, 0, 310, 165));
        pushButton_snap_catch = new QPushButton(groupBox_14);
        pushButton_snap_catch->setObjectName("pushButton_snap_catch");
        pushButton_snap_catch->setGeometry(QRect(10, 10, 50, 45));
        radioButton_16 = new QRadioButton(groupBox_14);
        radioButton_16->setObjectName("radioButton_16");
        radioButton_16->setEnabled(false);
        radioButton_16->setGeometry(QRect(80, 10, 130, 20));
        radioButton_17 = new QRadioButton(groupBox_14);
        radioButton_17->setObjectName("radioButton_17");
        radioButton_17->setEnabled(false);
        radioButton_17->setGeometry(QRect(80, 35, 130, 20));
        pushButton_8 = new QPushButton(groupBox_14);
        pushButton_8->setObjectName("pushButton_8");
        pushButton_8->setEnabled(false);
        pushButton_8->setGeometry(QRect(220, 10, 70, 45));
        checkBox_4 = new QCheckBox(groupBox_14);
        checkBox_4->setObjectName("checkBox_4");
        checkBox_4->setEnabled(false);
        checkBox_4->setGeometry(QRect(10, 60, 110, 22));
        label_19 = new QLabel(groupBox_14);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(10, 90, 50, 20));
        label_20 = new QLabel(groupBox_14);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(10, 115, 40, 20));
        checkBox_5 = new QCheckBox(groupBox_14);
        checkBox_5->setObjectName("checkBox_5");
        checkBox_5->setEnabled(false);
        checkBox_5->setGeometry(QRect(10, 140, 81, 20));
        snap_path_lineEdit = new QLineEdit(groupBox_14);
        snap_path_lineEdit->setObjectName("snap_path_lineEdit");
        snap_path_lineEdit->setGeometry(QRect(40, 90, 150, 25));
        pushButton_snap_path = new QPushButton(groupBox_14);
        pushButton_snap_path->setObjectName("pushButton_snap_path");
        pushButton_snap_path->setGeometry(QRect(210, 90, 50, 25));
        label_21 = new QLabel(groupBox_14);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(90, 140, 40, 20));
        lineEdit_2 = new QLineEdit(groupBox_14);
        lineEdit_2->setObjectName("lineEdit_2");
        lineEdit_2->setEnabled(false);
        lineEdit_2->setGeometry(QRect(120, 140, 80, 20));
        label_22 = new QLabel(groupBox_14);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(210, 140, 40, 20));
        radioButton_jpg = new QRadioButton(groupBox_14);
        radioButton_jpg->setObjectName("radioButton_jpg");
        radioButton_jpg->setEnabled(true);
        radioButton_jpg->setGeometry(QRect(40, 115, 50, 20));
        radioButton_png = new QRadioButton(groupBox_14);
        radioButton_png->setObjectName("radioButton_png");
        radioButton_png->setEnabled(true);
        radioButton_png->setGeometry(QRect(90, 115, 60, 20));
        radioButton_bmp = new QRadioButton(groupBox_14);
        radioButton_bmp->setObjectName("radioButton_bmp");
        radioButton_bmp->setGeometry(QRect(140, 115, 60, 20));
        radioButton_raw = new QRadioButton(groupBox_14);
        radioButton_raw->setObjectName("radioButton_raw");
        radioButton_raw->setGeometry(QRect(200, 115, 60, 20));
        frame_speed = new QFrame(centralWidget);
        frame_speed->setObjectName("frame_speed");
        frame_speed->setGeometry(QRect(1110, 560, 310, 35));
        frame_speed->setFrameShape(QFrame::Shape::StyledPanel);
        frame_speed->setFrameShadow(QFrame::Shadow::Raised);
        groupBox_speed = new QGroupBox(frame_speed);
        groupBox_speed->setObjectName("groupBox_speed");
        groupBox_speed->setGeometry(QRect(0, 0, 310, 35));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(1130, 545, 62, 17));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(1130, 360, 231, 17));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(1130, 105, 131, 17));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(1110, 5, 90, 17));
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(840, 510, 62, 17));
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(840, 430, 131, 17));
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(840, 200, 62, 17));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(840, 75, 62, 17));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(840, 5, 62, 17));
        MainWindow->setCentralWidget(centralWidget);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName("statusBar");
        statusBar->setMaximumSize(QSize(800, 16777215));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        groupBox_6->setTitle(QString());
        groupBox_4->setTitle(QString());
        groupBox_5->setTitle(QString());
        label->setText(QCoreApplication::translate("MainWindow", "Gamma", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Saturation", nullptr));
        groupBox_9->setTitle(QString());
        radioButton_collect->setText(QCoreApplication::translate("MainWindow", "Continuous", nullptr));
        radioButton_software_trigger->setText(QCoreApplication::translate("MainWindow", "Software", nullptr));
        radioButton_trigger_hardware->setText(QCoreApplication::translate("MainWindow", "Hardware", nullptr));
        software_trigger_once_button->setText(QCoreApplication::translate("MainWindow", "Single trigger", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Flash compensation", nullptr));
        groupBox_7->setTitle(QString());
        groupBox_8->setTitle(QString());
        flashlight_h->setText(QCoreApplication::translate("MainWindow", "High", nullptr));
        flashlight_l->setText(QCoreApplication::translate("MainWindow", "Low", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Polarity", nullptr));
        flashlight_auto->setText(QCoreApplication::translate("MainWindow", "Auto", nullptr));
        flashlight_manual->setText(QCoreApplication::translate("MainWindow", "Manual", nullptr));
        groupBox_11->setTitle(QString());
        groupBox_10->setTitle(QString());
        exposure_mode_auto->setText(QCoreApplication::translate("MainWindow", "Auto", nullptr));
        exposure_mode_manual->setText(QCoreApplication::translate("MainWindow", "Manual", nullptr));
        groupBox_12->setTitle(QString());
        label_3->setText(QCoreApplication::translate("MainWindow", "Brightness", nullptr));
        flicker_checkBox->setText(QCoreApplication::translate("MainWindow", "Anti-strobe", nullptr));
        radioButton_50HZ->setText(QCoreApplication::translate("MainWindow", "50HZ", nullptr));
        radioButton_60HZ->setText(QCoreApplication::translate("MainWindow", "60HZ", nullptr));
        groupBox_13->setTitle(QString());
        label_4->setText(QCoreApplication::translate("MainWindow", "Gain", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Exposure", nullptr));
        groupBox_2->setTitle(QString());
        checkBox_isp_h->setText(QCoreApplication::translate("MainWindow", "Horizontal flip", nullptr));
        checkBox_isp_v->setText(QCoreApplication::translate("MainWindow", "Vertical flip", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Sharpness", nullptr));
        groupBox->setTitle(QString());
        radioButton_B->setText(QCoreApplication::translate("MainWindow", "B", nullptr));
        radioButton_A->setText(QCoreApplication::translate("MainWindow", "A", nullptr));
        radioButton_C->setText(QCoreApplication::translate("MainWindow", "C", nullptr));
        pushButton_para_save->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        pushButton_para_acquiesce->setText(QCoreApplication::translate("MainWindow", "Default", nullptr));
        pushButton_para_load->setText(QCoreApplication::translate("MainWindow", "Load from file", nullptr));
        radioButton_D->setText(QCoreApplication::translate("MainWindow", "D", nullptr));
        groupBox_3->setTitle(QString());
        label_7->setText(QCoreApplication::translate("MainWindow", "This is monochrome camera, options are disabled", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Mode", nullptr));
        radioButton_AWB_auto->setText(QCoreApplication::translate("MainWindow", "Auto", nullptr));
        radioButton_13->setText(QCoreApplication::translate("MainWindow", "\346\211\213\345\212\250", nullptr));
        AWB_once_button->setText(QCoreApplication::translate("MainWindow", "White balance", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Red", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Green", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Blue", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Saturation", nullptr));
        groupBox_14->setTitle(QString());
        pushButton_snap_catch->setText(QCoreApplication::translate("MainWindow", "Capture", nullptr));
        radioButton_16->setText(QCoreApplication::translate("MainWindow", "Same as preview", nullptr));
        radioButton_17->setText(QCoreApplication::translate("MainWindow", "Custom ", nullptr));
        pushButton_8->setText(QCoreApplication::translate("MainWindow", "Set", nullptr));
        checkBox_4->setText(QCoreApplication::translate("MainWindow", "Ignore overlay", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Path", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Format", nullptr));
        checkBox_5->setText(QCoreApplication::translate("MainWindow", "Timing", nullptr));
        pushButton_snap_path->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Cycle", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "ms", nullptr));
        radioButton_jpg->setText(QCoreApplication::translate("MainWindow", "JPG", nullptr));
        radioButton_png->setText(QCoreApplication::translate("MainWindow", "PNG", nullptr));
        radioButton_bmp->setText(QCoreApplication::translate("MainWindow", "BMP", nullptr));
        radioButton_raw->setText(QCoreApplication::translate("MainWindow", "RAW", nullptr));
        groupBox_speed->setTitle(QString());
        label_13->setText(QCoreApplication::translate("MainWindow", "Speed", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Snapshot", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "ISP Color Processing", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Image adjustment", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Parameter", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "ISP Image Processing", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Exposure", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Trigger", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Resolution", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
